apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-worker-deployment
  labels:
    name: build-worker-deployment
    app: faasbase
spec:
  replicas: 6
  selector:
    matchLabels:
      app: faasbase
      name: build-worker-pod
  template:
    metadata:
      name: build-worker-pod
      labels:
        app: faasbase
        name: build-worker-pod
    spec:
      containers:
        - name: build-worker-pod
          image: 735683458704.dkr.ecr.us-west-2.amazonaws.com/build-worker:c289eb0359a8b2e64dc5bbb0f01d7a27e4342813
          ports:
            - containerPort: 8000
          env:
          - name: PORT
            value: "8000"
          - name: BUILD_REQUEST_SQS_URL
            value: https://sqs.us-west-2.amazonaws.com/735683458704/faasbase-build-request-queue
          - name: ENGINE_SERVICE_URL
            value: https://api.faasbase.com
          - name: DOCKER_HOST
            value: tcp://localhost:2375 
          envFrom:
          - secretRef:
              name: build-worker-secrets
        - name: dind
          image: "docker:dind"
          imagePullPolicy: Always
          command: ["dockerd", "--host", "tcp://127.0.0.1:2375"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: build-worker-storage
              mountPath: /var/lib/docker
              subPath: docker
            - name: build-worker-storage
              mountPath: /opt/build-worker
              subPath: build-worker
      volumes:
       - name: build-worker-storage
         emptyDir: {}