apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: faasbase
  region: us-west-2

nodeGroups:
  - name: ng-t2-large
    instanceType: t2.large
    desiredCapacity: 1
    volumeSize: 40