apiVersion: apps/v1
kind: Deployment
metadata:
  name: faasly-engine-service-deployment
  labels:
    name: faasly-engine-service-deployment
    app: faasly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faasly
  template:
    metadata:
      name: faasly-engine-service-pod
      labels:
        app: faasly
    spec:
      containers:
        - name: faasly-engine-service-pod
          image: 194872849581.dkr.ecr.us-west-2.amazonaws.com/faasly-engine-service:latest
          ports:
            - containerPort: 8000
          env:
          - name: PORT
            value: "8000"
          envFrom:
          - secretRef:
              name: faasly-engine-service-secrets
    