apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-worker-deployment
  labels:
    name: build-worker-deployment
    app: faasbase
spec:
  replicas: 6
  selector:
    matchLabels:
      app: faasbase
      name: build-worker-pod
  template:
    metadata:
      name: build-worker-pod
      labels:
        app: faasbase
        name: build-worker-pod
    spec:
      containers:
        - name: build-worker-pod
          image: 735683458704.dkr.ecr.us-west-2.amazonaws.com/build-worker:4d185eb922e73abb38858cc894f2bd8e382d3e6a
          ports:
            - containerPort: 8000
          env:
          - name: PORT
            value: "8000"
          - name: BUILD_REQUEST_SQS_URL
            value: https://sqs.us-west-2.amazonaws.com/735683458704/faasbase-build-request-queue
          - name: BUILD_SERVICE_URL
            value: http://build-worker-service
          - name: ENGINE_SERVICE_URL
            value: http://faasbase-engine-service
          - name: DOCKER_HOST 
            value: tcp://localhost:2375 
          envFrom:
          - secretRef:
              name: build-worker-secrets
        - name: dind-daemon 
          image: docker:20.10-dind
          securityContext: 
              privileged: true