# name: Deploy Web Console to Server
# on:
#   push:
#     paths:
#       - "console/**"
#     branches:
#       - main
# jobs:
#   run:
#     runs-on: ubuntu-latest
#     env:
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       CI: false
#       VITE_APP_BACKEND_URL: https://api.faasbase.com
#       VITE_APP_FRONTEND_URL: https://app.faasbase.com
#       VITE_APP_AUTH0_CLIENT_ID: PVL9H8hSiUxfBm06kUH9zDzeGbIJsirX
#       VITE_APP_AUTH0_DOMAIN: dev-d0m2qkwao0zc3lbs.us.auth0.com
#       VITE_APP_AUTH0_AUDIENCE: https://api.faasbase.com
#     steps:
#       - uses: actions/checkout@v2

#       - name: Install dependencies
#         run: cd console && npm install

#       - name: Build
#         run: cd console && npm run build
      
#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-west-2

#       - name: Deploy Console to Bucket
#         run: aws s3 sync ./console/dist/ s3://app.faasbase.com/

#       - name: Invalidate dashboard cloudfront
#         run: aws cloudfront create-invalidation --distribution-id EHRY1BYNH6AO1 --paths "/*"